GET http://localhost:3000/api/v1/refresh-token
Cookie: jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3QyQHRlc3QuY29tIiwiaWF0IjoxNjYwODIzODM0LCJleHAiOjE2NjA5MTAyMzR9.esScagl1Tf5tHL7vwiUZhQnSZpcslfo5ILOTlBqS7Z0

###
POST http://localhost:3000/api/v1/login
Content-Type: application/json

{
  "email":"test2@test.com",
  "password":"1234"
}

###
GET http://localhost:3000/api/v1/logout